name: dart_polymer_examples
description: A sample web application
homepage: https://github.com/sethladd/dart-polymer-dart-examples
dependencies:
  google_oauth2_client: any
  google_plus_v1_api: any
  js: any
  polymer: '>= 0.8.0'
